feat(thumb): add thumb apis in media
chiflix/apis pull request #2
Opened 2018-11-01 06:56 UTC by shiyunjin

2018-11-01 07:19 UTC, shiyunjin commented on media/v1/media.proto
> +  };
用户发送media_hash到服务器获取缩略图列表，会返回服务器目前拥有的缩略图id数组类似：[1, 2, 3, 5, 6, 7, 8]

2018-11-01 07:20 UTC, shiyunjin commented on media/v1/media.proto
> +    };
用户发送media_hash到服务器获取缩略图列表，会返回服务器目前拥有的缩略图id数组类似：[1, 2, 3, 5, 6, 7, 8]

2018-11-01 07:26 UTC, shiyunjin commented on media/v1/media.proto
> +      body: "*"
用户收到列表可以通过media_hash和id列表获取缩略图，如发送请求的列表[1, 2, 3, 5, 6]，其数量可由前端控制，动态调节获取的位置和数量，返回{"1":rawimage,"2":rawimage,"3":rawimage,"5":rawimage,"6":rawimage}

2018-11-01 07:32 UTC, shiyunjin commented on media/v1/media.proto
> +      body: "*"
本地生成缩略图并进行压缩或webp转换(推荐webp)后直接进行上传{"id":1,"payload":rawdata,"md5":"xxxx"}，在服务端进行二次md5校验，并记录图像大小方便之后择优问题：如截图黑屏或者由于用户本地原因截图出透明图，返回grpc-status

2018-11-05 09:26 UTC, tomasen requested changes

2018-11-05 09:26 UTC, tomasen commented on media/v1/media.proto
> +    repeated int64 have = 2;
这是什么？ 名字起得不太好

2018-11-05 09:26 UTC, tomasen commented on media/v1/media.proto
> +  string md5 = 3;
为什么有md5

2018-11-05 09:29 UTC, shiyunjin commented on media/v1/media.proto
> +  string md5 = 3;
2个原因，第一个是校验客户端要传的数据和给的payload的正确性，第二点是记录文件hash，如果其他客户端上传缩略图可进行比对是否是相同的

2018-11-05 09:31 UTC, shiyunjin commented on media/v1/media.proto
> +    repeated int64 have = 2;
嗯，确实这个是一个[1, 2, 3, 5, 6, 7, 8]类似这样的index数组 ，方便客户端知道服务器上现在对于这个视频目前有编号多少的缩略图，方便客户端判断是否要获取或者生成上传

2018-11-06 08:00 UTC, tomasen requested changes

2018-11-06 08:00 UTC, tomasen commented on media/v1/media.proto
> +  repeated int64 children = 3;
这是啥

2018-11-06 08:00 UTC, tomasen commented on media/v1/media.proto
> +message ThumbRange {
只被使用一次的 message 可以定义在使用这个 message 的内部。不用定义成 global

2018-11-06 08:00 UTC, tomasen commented on media/v1/media.proto
> +  bytes context =1;
context 是上下文的意思。
你是不是想说 payload 或者 content

2018-11-06 08:04 UTC, shiyunjin commented on media/v1/media.proto
> +  repeated int64 children = 3;
这是之前那个have，我再想想

2018-11-08 08:23 UTC, closed without merging

2018-11-08 08:24 UTC, tomasen commented
api 重新起草。 closed